file_format: "1"
id: kyria_dongle
name: Kyria Dongle
type: shield
url: https://splitkb.com/products/kyria-pcb-kit
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - kyria_dongle_central
  - kyria_dongle_left
  - kyria_dongle_right
