manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Benaan
      url-base: https://github.com/Benaan
  projects:
    - name: zmk
      remote: Benaan
      revision: main
      import: app/west.yml
  self:
    path: config
