file_format: "1"
id: souffle
name: souffle
type: shield
url: https://github.com/sadekbaroudi/sweep36
requires: [pro_micro]
features:
  - keys
siblings:
  - souffle_left
  - souffle_right
  - souffle_central